"""owner de post ajouté

Revision ID: a92a3ddcf0e3
Revises: b9e83f7a9344
Create Date: 2022-01-31 13:11:59.581926
il semble que owner ne soit pas une colonne finalement
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a92a3ddcf0e3'
down_revision = 'b9e83f7a9344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
